FROM ubuntu:19.04

MAINTAINER davidjguru <davidjguru@gmail.com>

RUN apt update && apt -y upgrade && \
    apt install -y apache2 php7.3 libapache2-mod-php \
    php-mysql build-essential apt-transport-https \
    ca-certificates jq curl software-properties-common \
    file mysql-client unzip rsync vim nano git && \
    apt install           \
    php7.3                \
    php7.3-bcmath         \
    php7.3-bz2            \
    php7.3-curl           \
    php7.3-dev            \
    php7.3-gd             \
    php7.3-dom            \
    php7.3-imap           \
    php7.3-imagick        \
    php7.3-intl           \
    php7.3-json           \
    php7.3-ldap           \
    php7.3-mbstring       \
    php7.3-mysql          \
    php7.3-oauth          \
    php7.3-odbc           \
    php7.3-uploadprogress \
    php7.3-ssh2           \
    php7.3-xml            \
    php7.3-yaml           \
    php7.3-solr           \
    php7.3-zip            \
    php7.3-apcu           \
    php7.3-opcache        \
    php7.3-redis          \
    php7.3-opcache        \
    php7.3-memcached      \
    php7.3-xdebug         \
    libapache2-mod-php7.3
